#!/bin/bash
# entrypoint.sh — Runs before PiClaw starts.
# Syncs baked-in Drupal skills/templates/config to the mounted workspace.

set -e

WORKSPACE="/workspace"
SKILLS_SRC="/home/agent/.pi/skills"
TEMPLATES_SRC="/home/agent/.pi/templates"

# -- Sync Drupal skills to workspace --
if [[ -d "$SKILLS_SRC" ]]; then
  mkdir -p "$WORKSPACE/.pi/skills"
  for skill_dir in "$SKILLS_SRC"/*/; do
    if [[ -d "$skill_dir" ]]; then
      skill_name=$(basename "$skill_dir")
      if [[ ! -f "$WORKSPACE/.pi/skills/$skill_name/SKILL.md" ]] || \
         [[ "$skill_dir/SKILL.md" -nt "$WORKSPACE/.pi/skills/$skill_name/SKILL.md" ]]; then
        cp -r "$skill_dir" "$WORKSPACE/.pi/skills/"
      fi
    fi
  done
fi

# -- Sync templates --
if [[ -d "$TEMPLATES_SRC" ]]; then
  mkdir -p "$WORKSPACE/.piclaw/stack"
  for tpl in "$TEMPLATES_SRC"/*; do
    tpl_name=$(basename "$tpl")
    if [[ ! -f "$WORKSPACE/.piclaw/stack/$tpl_name" ]] || \
       [[ "$tpl" -nt "$WORKSPACE/.piclaw/stack/$tpl_name" ]]; then
      cp "$tpl" "$WORKSPACE/.piclaw/stack/"
    fi
  done
fi

# -- Sync config (always overwrite — ensures DrupalClaw config is applied) --
AGENT_CONFIG="/home/agent/.pi/agent"
mkdir -p "$WORKSPACE/.piclaw"
cp "$AGENT_CONFIG/AGENTS.md" "$WORKSPACE/AGENTS.md" 2>/dev/null || true
cp "$AGENT_CONFIG/dev-panel.json" "$WORKSPACE/.piclaw/dev-panel.json" 2>/dev/null || true

# -- Generate .env.sh with branding (only if missing) --
if [[ ! -f "$WORKSPACE/.env.sh" ]]; then
  ICON_PATH="/home/agent/.pi/assets/drupal_claw_icon.png"
  AVATAR_DATA=""
  if [[ -f "$ICON_PATH" ]]; then
    AVATAR_B64=$(base64 "$ICON_PATH" | tr -d '\n')
    AVATAR_DATA="data:image/png;base64,${AVATAR_B64}"
  fi

  cat > "$WORKSPACE/.env.sh" << EOF
# DrupalClaw environment — auto-generated by entrypoint.sh
export PICLAW_ASSISTANT_NAME="DrupalClaw"
EOF
  if [[ -n "$AVATAR_DATA" ]]; then
    echo "export PICLAW_ASSISTANT_AVATAR=\"${AVATAR_DATA}\"" >> "$WORKSPACE/.env.sh"
  fi
fi

# -- Fix Docker socket permissions (lost on Docker Desktop restart) --
chmod 666 /var/run/docker.sock 2>/dev/null || true

# -- Ensure DrupalClaw redirect is in place (overrides any stale PiClaw index.html) --
# Find static dir dynamically — path can vary across PiClaw versions and platforms
PICLAW_STATIC=$(find /usr/local/lib/bun -path "*/piclaw/runtime/web/static" -type d 2>/dev/null | head -1)
if [[ -n "$PICLAW_STATIC" ]]; then
  echo '<!DOCTYPE html><html><head><script>window.location.replace("/static/drupalclaw/index.html")</script></head><body></body></html>' \
    > "$PICLAW_STATIC/index.html"
fi

# -- Hand off to original PiClaw entrypoint --
exec /entrypoint-piclaw.sh "$@"
